### ISSUE TITLE
check vs traverse

### ISSUE THREAD

**Issue by oculus42** [derekdorr/skald#2]
The docs for `check` show and example of `traverse`, and inside `check.js` the function is internally called `traverse` before export. I think traverse makes more sense, but either way is fine, so long as it is consistent.

**Comment by derekdorr** [comment]
Agreed. Originally called it traverse, then changed to check, though I like traverse. Will create traverse and alias check to that for backwards compatibility for a bit.

**Comment by derekdorr** [comment]
Closing.
